### ISSUE TITLE
straight motion not working on kilombo

### ISSUE THREAD

**Issue by juliajmg** [JIC-CSB/kilombo#45]
Hi, 

I am using kilombo as my chosen simulator for kilobots (very good, by the way!) but i have one issue: 

The set_motion() function for going straight is not working on the examples (follow and orbit), although they turn right and left with the same function.
 

I looked into the src code files, and could be related to the variable and function declaration for straight motion on skilobot.c and kbapi.c  , but i just can’t figure it out. 

Is this a general bug or is just me that has this issue? 

Thanks!

**Comment by fjansson** [comment]
Hi Julia, this indeed seems to be a bug, thanks for reporting it!.
As a quick work-around, changing `kilo_straight_left and `kilo_straight_right` from 7 to 75 in `src/kbapi.c` fixes this.

I think this bug was introduced in 0f6df00390b with the changes to the motion model, and has something to do with the thresholds in `set_speeds()` in `skilobot.c`.

**Comment by juliajmg** [comment]
Thank you!! I changed it and now is working. 
Glad to help!
